unused_event = [
    
    "EVT_TWEAK_L",
    "EVT_TWEAK_M",
    "EVT_TWEAK_R",

    "TIMER",
    "TIMER0",
    "TIMER1",
    "TIMER2",
    "TIMER_JOBS",
    "TIMER_AUTOSAVE",
    "TIMER_REPORT",
    "TIMERREGION",
    
    ]

used_event = [
    
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",

    "ZERO",
    "ONE",
    "TWO",
    "THREE",
    "FOUR",
    "FIVE",
    "SIX",
    "SEVEN",
    "EIGHT",
    "NINE",

    "OSKEY",
    "APP",
    "GRLESS",

    "RET",
    "LINE_FEED",
    "BACK_SPACE",
    "DEL",

    "SEMI_COLON",
    "PERIOD",
    "COMMA",
    "QUOTE",
    "ACCENT_GRAVE",
    "MINUS",
    "PLUS",
    "SLASH",
    "BACK_SLASH",

    "EQUAL",
    "LEFT_BRACKET",
    "RIGHT_BRACKET",

    "NUMPAD_2",
    "NUMPAD_4",
    "NUMPAD_6",
    "NUMPAD_8",
    "NUMPAD_1",
    "NUMPAD_3",
    "NUMPAD_5",
    "NUMPAD_7",
    "NUMPAD_9",

    "NUMPAD_PERIOD",
    "NUMPAD_SLASH",
    "NUMPAD_ASTERIX",
    "NUMPAD_0",
    "NUMPAD_MINUS",
    "NUMPAD_ENTER",
    "NUMPAD_PLUS",

    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "F13",
    "F14",
    "F15",
    "F16",
    "F17",
    "F18",
    "F19",
    "F20",
    "F21",
    "F22",
    "F23",
    "F24",

    "PAUSE",
    "INSERT",
    "HOME",
    "PAGE_UP",
    "PAGE_DOWN",
    "END",

    "MEDIA_PLAY",
    "MEDIA_STOP",
    "MEDIA_FIRST",
    "MEDIA_LAST",
    "TEXTINPUT",
    "WINDOW_DEACTIVATE",

    "NDOF_MOTION",
    "NDOF_BUTTON_MENU",
    "NDOF_BUTTON_FIT",
    "NDOF_BUTTON_TOP",
    "NDOF_BUTTON_BOTTOM",
    "NDOF_BUTTON_LEFT",
    "NDOF_BUTTON_RIGHT",
    "NDOF_BUTTON_FRONT",
    "NDOF_BUTTON_BACK",
    "NDOF_BUTTON_ISO1",
    "NDOF_BUTTON_ISO2",
    "NDOF_BUTTON_ROLL_CW",
    "NDOF_BUTTON_ROLL_CCW",
    "NDOF_BUTTON_SPIN_CW",
    "NDOF_BUTTON_SPIN_CCW",
    "NDOF_BUTTON_TILT_CW",
    "NDOF_BUTTON_TILT_CCW",
    "NDOF_BUTTON_ROTATE",
    "NDOF_BUTTON_PANZOOM",
    "NDOF_BUTTON_DOMINANT",
    "NDOF_BUTTON_PLUS",
    "NDOF_BUTTON_MINUS",
    "NDOF_BUTTON_ESC",
    "NDOF_BUTTON_ALT",
    "NDOF_BUTTON_SHIFT",
    "NDOF_BUTTON_CTRL",
    "NDOF_BUTTON_1",
    "NDOF_BUTTON_2",
    "NDOF_BUTTON_3",
    "NDOF_BUTTON_4",
    "NDOF_BUTTON_5",
    "NDOF_BUTTON_6",
    "NDOF_BUTTON_7",
    "NDOF_BUTTON_8",
    "NDOF_BUTTON_9",
    "NDOF_BUTTON_10",
    "NDOF_BUTTON_A",
    "NDOF_BUTTON_B",
    "NDOF_BUTTON_C",

    "ACTIONZONE_AREA",
    "ACTIONZONE_REGION",
    "ACTIONZONE_FULLSCREEN",

    ]

shortcut_event = [

    "ESC",
    "SPACE",

    "DOWN_ARROW",
    "UP_ARROW",

    "H",

    "LEFT_ALT",
    "RIGHT_ALT",

    "TAB",

    ]

passthrough_event = [

    "MOUSEMOVE",
    "INBETWEEN_MOUSEMOVE",
    "TRACKPADPAN",
    "TRACKPADZOOM",
    "MOUSEROTATE" ,
    "MOUSESMARTZOOM",
    "WHEELUPMOUSE",
    "WHEELDOWNMOUSE",
    "WHEELINMOUSE",
    "WHEELOUTMOUSE",

    "MIDDLEMOUSE", 
    "LEFTMOUSE",
    "RIGHTMOUSE",
    "BUTTON4MOUSE",
    "BUTTON5MOUSE",
    "BUTTON6MOUSE",
    "BUTTON7MOUSE",
    "PEN",
    "ERASER",

    "LEFT_ARROW",
    "RIGHT_ARROW",

    "LEFT_CTRL",
    "RIGHT_CTRL",

    "LEFT_SHIFT",
    "RIGHT_SHIFT",

    ]